version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./models:/app/models
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend 